### ISSUE TITLE
manually create the IAM user with least-privilege permissions instead of AdministratorAccess

### ISSUE THREAD

**Issue by hellodword** [harryzcy/mailbox#310]
https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege

What I need to do is just applying these "Actions" right?

https://github.com/harryzcy/mailbox/blob/607523208b2bbc1d261426afd15ecbea58c673ad/serverless.yml.example#L18-L54

**Comment by harryzcy** [comment]
Not really. This project is using [serverless](https://github.com/serverless/serverless), which then will call CloudFormation to deploy everything.

The permission above is for actual Lambda functions, not for deployment process itself. The actual required permission are anything related to CloudFormation, and those that deploy things to Lambda, DynamoDB, API Gateway, etc.

https://docs.aws.amazon.com/prescriptive-guidance/latest/least-privilege-cloudformation/introduction.html

**Comment by harryzcy** [comment]
@hellodword Can you try adding permission to S3 bucket as documented here: https://docs.aws.amazon.com/ses/latest/dg/receiving-email-permissions.html. Probably I should update README about this.

> BTW, the quick-start.sh is out of date, I followed the template yml to generate this, should I open a new issue about more detailed docs?

I think I'll document that `serverless.yml.example` is the source of truth. The script is kind of hard to maintain, and I might just remove it in the future. I feel copying over example should be simpler.

**Comment by harryzcy** [comment]
Can you please share some logs from CloudWatch? Go to Log Groups -> `/aws/lambda/<function-name>`. There should have one log group per Lambda function. Those from `/aws/lambda/*-emailsList` would be useful.

**Comment by harryzcy** [comment]
> The listed emails can not be "read" after clicking in the browser.

Do you mean emails still show as "not read"?

> Meanwhile, the cli will get 500 without error details:

Yeah the error message needs improvements, both for cli and web.

**Comment by harryzcy** [comment]
Interesting... By the way, did you use double click? The UI logic is double click opens the email, and single click selects it.

If it's still not working, do you see any errors in browser console, and can you check the networking page in the console, if a request gets sent to `web/emails/<id>`. Thanks

**Comment by harryzcy** [comment]
@hellodword Hi, just following up here. Are the issues solved? If there's no additional issues, I'm planning to close it.

**Comment by harryzcy** [comment]
Thanks. Feel free to open a new issue if there are other problems.
