### ISSUE TITLE
Any plan of supporting Catch-All?

### ISSUE THREAD

**Issue by hellodword** [harryzcy/mailbox#313]
I believe [catch-all email address](https://www.google.com/search?q=catch-all+email+address) or [wildcard email address](https://www.google.com/search?q=wildcard+email+address) is useful for custom domain emails.

- Catch-All address
- reject/discard all directly emails sent to the Catch-All address
- ability of replying any email from Catch-All email box with different `from` automatically

How do you think?

**Comment by harryzcy** [comment]
> * Catch-All address

It's supported. Any email that SES receives will appear in the same inbox. You can even use multiple domains.

> * reject/discard all directly emails sent to the Catch-All address

So you would want to keep emails sent to some configured email addresses, and reject everything else? It could be an improvement.

> * ability of replying any email from Catch-All email box with different `from` automatically

It should be the case as well when using mailbox-browser. You need to set `EMAIL_ADDRESSES` environment variable. It should list all addresses that you're allowed (want) to sent from in SES. It's implemented here: harryzcy/mailbox-browser#214.
e.g. `EMAIL_ADDRESSES=email@gmail.com,my-domain.com` permits `email@gmail.com` and any address from `my-domain.com`. The `from` address will be auto set if it's in the allowed list.

**Comment by harryzcy** [comment]
Which part specifically what you want to know?
For the aws part, I'm still deploying directly from my command line right now. For mailbox-browser, I'm spinning up a docker container, and I'm using the yaml file for configurations (just found out it's not well documented, I should do this), but environment variable should work just fine.

**Comment by harryzcy** [comment]
> Which clients are you using on iOS/Android/Windows/macOS/Linux and how do you use them with mailbox?

I'm building and using them on macOS.

> Using A catch-all custom domain email with SMTP support or [forwarding all emails to your main email address such as a Gmail](https://medium.com/@yjzhang.me/forwarding-personal-domain-emails-to-gmail-with-aws-lambda-and-cloudformation-4a7208af4eb8)?

SMTP protocol is not yet implemented, and I'm not sure if it's possible with AWS Lambda. Regarding the forwarding feature, the link you provide actually works great. You can actually use that repo and this repo at the same time, just let SES trigger two lambda functions. I prefer not to reimplement them.
